development:
  url: 'http://7burns.dyndns.org:8080/jasperserver/'
  username: 'jasperadmin'
  password: 'gr1ff1th'

test:
  url: 'http://server:port/jasperserver/'
  username: 'username'
  password: 'password'

production:
  url: 'http://server:port/jasperserver/'
  username: 'username'
  password: 'password'
